modLoader = "kotlinforforge"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/jimgreer/pilot/issues"
license = "Apache-2.0"

[[mods]]
modId = "pilot"
version = "${version}"
displayName = "Pilot"
authors = "jgreer"
description = '''
A VS2 addon that creates entities to control Create's Redstone Links
'''

[[dependencies.pilot]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pilot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pilot]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.1.3-beta.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.pilot]]
modId = "create"
mandatory = true
versionRange = "[0.5.1,)"
ordering = "AFTER"
side = "BOTH"